CLASS LHC_BOOKING DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      CALCULATEBOOKINGID FOR DETERMINE ON SAVE
        IMPORTING
          KEYS FOR  BOOKING~CALCULATEBOOKINGID ,
      CALCULATETOTALPRICE FOR DETERMINE ON MODIFY
        IMPORTING KEYS FOR BOOKING~CALCULATETOTALPRICE.
ENDCLASS.

CLASS LHC_BOOKING IMPLEMENTATION.
  METHOD CALCULATEBOOKINGID.
  ENDMETHOD.
  METHOD CALCULATETOTALPRICE.
    " Read all parent UUIDs
    READ ENTITIES OF ZI_FE_TRAVEL_000247 IN LOCAL MODE
    ENTITY BOOKING BY \_TRAVEL
        FIELDS ( TRAVELUUID  )
        WITH CORRESPONDING #(  KEYS  )
    RESULT DATA(TRAVELS).

    " Trigger Re-Calculation on Root Node
    MODIFY ENTITIES OF ZI_FE_TRAVEL_000247 IN LOCAL MODE
    ENTITY TRAVEL
        EXECUTE RECALCTOTALPRICE
        FROM CORRESPONDING  #( TRAVELS ).
  ENDMETHOD.

ENDCLASS.
