CLASS LHC_TRAVEL DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
        REQUEST REQUESTED_AUTHORIZATIONS FOR TRAVEL
        RESULT RESULT,
      CALCULATETRAVELID FOR DETERMINE ON SAVE
        IMPORTING
          KEYS FOR  TRAVEL~CALCULATETRAVELID ,
      RECALCTOTALPRICE FOR MODIFY
        IMPORTING KEYS FOR ACTION TRAVEL~RECALCTOTALPRICE,
      CALCULATETOTALPRICE FOR DETERMINE ON MODIFY
        IMPORTING KEYS FOR TRAVEL~CALCULATETOTALPRICE.
ENDCLASS.

CLASS LHC_TRAVEL IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
  METHOD CALCULATETRAVELID.
    READ ENTITIES OF ZI_FE_TRAVEL_000247 IN LOCAL MODE
      ENTITY TRAVEL
        ALL FIELDS WITH CORRESPONDING #( KEYS )
      RESULT DATA(ENTITIES).
    DELETE ENTITIES WHERE TRAVELID IS NOT INITIAL.
    CHECK ENTITIES IS NOT INITIAL.
    "Dummy logic to determine object_id
    SELECT MAX( TRAVEL_ID ) FROM ZFE_ATRAV_000247 INTO @DATA(MAX_OBJECT_ID).
    "Add support for draft if used in modify
    "SELECT SINGLE FROM FROM ZFE_DTRAV_000247 FIELDS MAX( TravelID ) INTO @DATA(max_orderid_draft). "draft table
    "if max_orderid_draft > max_object_id
    " max_object_id = max_orderid_draft.
    "ENDIF.
    MODIFY ENTITIES OF ZI_FE_TRAVEL_000247 IN LOCAL MODE
      ENTITY TRAVEL
        UPDATE FIELDS ( TRAVELID )
          WITH VALUE #( FOR ENTITY IN ENTITIES INDEX INTO I (
          %TKY          = ENTITY-%TKY
          TRAVELID     = MAX_OBJECT_ID + I
    ) ).
  ENDMETHOD.
  METHOD RECALCTOTALPRICE.
    TYPES : BEGIN OF LTS_AMT_PER_CURR,
              AMOUNT        TYPE /DMO/TOTAL_PRICE,
              CURRENCY_CODE TYPE /DMO/CURRENCY_CODE,
            END OF LTS_AMT_PER_CURR.

    DATA LT_AMT_PER_CURR TYPE TABLE OF LTS_AMT_PER_CURR.

    READ ENTITIES OF ZI_FE_TRAVEL_000247 IN LOCAL MODE
      ENTITY TRAVEL
        FIELDS ( BOOKINGFEE CURRENCYCODE )
        WITH CORRESPONDING #( KEYS )
      RESULT DATA(LT_TRAVELS).


    DELETE LT_TRAVELS WHERE CURRENCYCODE IS INITIAL.

    LOOP AT LT_TRAVELS ASSIGNING FIELD-SYMBOL(<LS_TRAVEL>).
      " Set the start for the calculation by adding the booking fee.
      LT_AMT_PER_CURR = VALUE #( ( AMOUNT = <LS_TRAVEL>-BOOKINGFEE
                                   CURRENCY_CODE = <LS_TRAVEL>-CURRENCYCODE ) ).


      " Read all associated bookings and add them to the total price.
      READ ENTITIES OF ZI_FE_TRAVEL_000247 IN LOCAL MODE
          ENTITY TRAVEL BY \_BOOKING
          FIELDS ( FLIGHTPRICE CURRENCYCODE )
          WITH VALUE #( ( %TKY = <LS_TRAVEL>-%TKY ) )
          RESULT DATA(LT_BOOKINGS).

      LOOP AT LT_BOOKINGS ASSIGNING FIELD-SYMBOL(<LS_BOOKING>) WHERE CURRENCYCODE IS NOT INITIAL.
        COLLECT VALUE LTS_AMT_PER_CURR( AMOUNT        = <LS_BOOKING>-FLIGHTPRICE
                                        CURRENCY_CODE = <LS_BOOKING>-CURRENCYCODE ) INTO LT_AMT_PER_CURR.
      ENDLOOP.

      CLEAR <LS_TRAVEL>-TOTALPRICE.

      LOOP AT LT_AMT_PER_CURR INTO DATA(LS_AMT).
        IF LS_AMT-CURRENCY_CODE EQ <LS_TRAVEL>-CURRENCYCODE.
          <LS_TRAVEL>-TOTALPRICE += LS_AMT-AMOUNT.
        ELSE.
          /DMO/CL_FLIGHT_AMDP=>CONVERT_CURRENCY(
            EXPORTING
              IV_AMOUNT               = LS_AMT-AMOUNT
              IV_CURRENCY_CODE_SOURCE = LS_AMT-CURRENCY_CODE
              IV_CURRENCY_CODE_TARGET = <LS_TRAVEL>-CURRENCYCODE
              IV_EXCHANGE_RATE_DATE   = CL_ABAP_CONTEXT_INFO=>GET_SYSTEM_DATE( )
            IMPORTING
              EV_AMOUNT               = DATA(LV_AMT)
          ).

          <LS_TRAVEL>-TOTALPRICE += LV_AMT.
        ENDIF.
      ENDLOOP.

    ENDLOOP.

    " Modify total_price field of TRAVELS
    MODIFY ENTITIES OF ZI_FE_TRAVEL_000247 IN LOCAL MODE
      ENTITY TRAVEL
        UPDATE FIELDS ( TOTALPRICE )
        WITH CORRESPONDING #( LT_TRAVELS ).


  ENDMETHOD.

  METHOD CALCULATETOTALPRICE.
    MODIFY ENTITIES OF ZI_FE_TRAVEL_000247 IN LOCAL MODE
      ENTITY TRAVEL
      EXECUTE RECALCTOTALPRICE
      FROM CORRESPONDING #( KEYS ).

  ENDMETHOD.

ENDCLASS.
